"files": [
  {
    "source": "/BTPanel/languages/uk/*.json",
    "translation": "/BTPanel/languages/uk/%original_file_name%",
    "import_translations": true,
    "export_pattern": "/BTPanel/languages/uk/%original_file_name%"
  },
  {
    "source": "/BTPanel/static/vite/lang/uk/*.json",
    "translation": "/BTPanel/static/vite/lang/uk/%original_file_name%",
    "import_translations": true,
    "export_pattern": "/BTPanel/static/vite/lang/uk/%original_file_name%"
  }
]
