name: Download Translations from Crowdin

on:
  workflow_dispatch:  # Запуск вручну

jobs:
  download_translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download translations from Crowdin
      env:
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}  # Токен API
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}  # ID проекту
      run: |
        # Отримуємо список мов перекладів
        LANGUAGES=("uk" "en" "fr")  # Вкажіть мови, які вам потрібні
        
        for LANG in "${LANGUAGES[@]}"; do
          echo "Завантаження перекладів для мови: $LANG"
          
          # Запит для отримання перекладу
          curl -L -o "$LANG.json" "https://api.crowdin.com/api/v2/projects/$CROWDIN_PROJECT_ID/translations/$LANG" \
          -H "Authorization: Bearer $CROWDIN_API_TOKEN" || echo "Не вдалося завантажити $LANG.json"
        done

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add *.json  # Додаємо всі файли з перекладами
        git commit -m "Update translations from Crowdin" || echo "No changes to commit"
        git push
