name: Download Translations from Crowdin

on:
  workflow_dispatch:  # Запуск вручну

jobs:
  download_translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download translations from Crowdin
      uses: crowdin/github-action@v2
      with:
        download_translations: true
        token: ${{ secrets.CROWDIN_API_TOKEN }}
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        localization_branch_name: 'main'  # Гілка для завантаження перекладів у GitHub
        download_language: 'uk'  # Вказати мову для завантаження
        push_translations: true  # Пуш перекладів в гілку
        # Додаткові параметри, якщо потрібно:
        export_only_approved: true  # Завантажити лише затверджені переклади

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update translations from Crowdin" || echo "No changes to commit"
        git push
