name: Download Translations from Crowdin

on:
  workflow_dispatch:  # Дозволяє запускати workflow вручну

jobs:
  download_translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download translations from Crowdin
      run: |
        # Отримуємо список файлів перекладів з Crowdin
        files=$(curl -X GET "https://api.crowdin.com/api/v2/projects/${{ secrets.CROWDIN_PROJECT_ID }}/translations" \
        -H "Authorization: Bearer ${{ secrets.CROWDIN_API_TOKEN }}" | jq -r '.data[].name')

        # Завантажуємо переклади для кожного файлу
        for file in $files; do
          echo "Завантаження перекладу для $file"
          curl -X GET "https://api.crowdin.com/api/v2/projects/${{ secrets.CROWDIN_PROJECT_ID }}/translations/${file}" \
          -H "Authorization: Bearer ${{ secrets.CROWDIN_API_TOKEN }}" \
          -o "$file" # Зберігаємо переклад в файл з такою ж назвою
        done

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .  # Додаємо всі зміни
        git commit -m "Update translations from Crowdin" || echo "No changes to commit"
        git push
